### PR TITLE
Update grammar matcher for newer Atom editor

### PR DESCRIPTION
**Pull request by jtwalters**
The snippets weren't working since PHP is now `text.html.php`. I made the change and bumped the version to 2.0.0.

### CODE REVIEW

**Comment by robballou** [comment]
Looks good to me. I think we can get rid of the version bump because `apm publish` can handle that. Thanks for this update :)

**Comment by jtwalters** [comment]
I removed the version bump.

**Comment by robballou** [comment]
Out of curiosity, are you still seeing the PHP scope change? I think there was an issue with 0.197 that changed things but then 0.198 fixed it. If so I can roll this in (I still see source.php in the scopes for files).

**Comment by michaelfavia** [comment]
I tested our master just now and im not having any trouble with snippets in module files or install files. If there another file type that can reproduce the issue? That said i inspected the ATOM chromium dom and DID notice that the "data-grammar" attr is now "text html php". 

I dont see any reason not to merge these changes as it seems more correct and still worked after i applied the PR. merging into master if rob signs off ill tag a release.

**Comment by robballou** [comment]
@michaelfavia @jtwalters works for me! :)

**Comment by michaelfavia** [comment]
New version pushed. Thank you all! @robballou and @jtwalters!

@robballou: should you want to in the future, you should be able to deploy new versions with apm as well.

**Pull request merged**
